table 'Territory Lookup'
	lineageTag: 5ef5acfe-89f7-4df0-a988-2da61fde61a9

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 8e9a5c9b-0955-49bd-89ff-5e84fdb3ff59
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: dd20779c-7b0d-44df-9e33-4fcd643868c1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: d7923e92-3d6f-4b05-9a2c-52eeb39a1262
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: b45ddb3d-8544-46bd-941e-2b5fff60819b
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition 'Territory Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MG588DU\OneDrive - EY\Documents\PowerBI\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Territory Lookup.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesTerritoryKey", Int64.Type}, {"Region", type text}, {"Country", type text}, {"Continent", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

